version: "3.9"
services:
  api:
    build: ./backend
    container_name: aireclaro-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  web:
    build: ./frontend
    container_name: aireclaro-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - api
    restart: unless-stopped
